ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDSzCCAjOgAwIBAgIQeexsxsoLip/Lr+Kkiy8N3zANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMwNTExMTg1MjIwWhcNMzMw
  NTA4MTg1MjIwWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
  SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC8m5m9yHtUEK4Yhmih7/zMYt6wukLupHRc
  cca8zbs7t71+HOTWYoGgpbx5xD432Rm0HykbR5P4IPYUoYmHA1o4tTKqN9HCSQS8
  kENnxxqk9+Nmig2b3pNHgxvMM3pT1WCajwXOQ7L02kmW3Ud9UmyUpCOy6xIpQ2d8
  rgAeZqnDkvSq5Nn1kNHjVef86cotr/Pj7MS6M68cEsRrURJBDieRpKdrrLmHV5If
  PnBUbA5k+h1mUFb4A1Tn0x2xwBGPf9Mi9L4lideAaWwLiBI9EtHqwZ+4P6uePun5
  f6hDayl8cu7UrL7jOKBYJ+OkRP2n3uVxMB4Y1B+DnK4hIt9KzESVAgMBAAGjgYww
  gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
  AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRKk81t/KqMrTqFZk+naRTeOLkO
  VTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
  hkiG9w0BAQsFAAOCAQEAb8EEXhLj9PxqY59V5przYGSDDoNCf0COZRbqIiGmJ1cv
  Yct38kLtNCct8vfk9tY6273Yd6jP2GuYo7BPqPJmThm0KBUS4bnp2yxImzwB2kLF
  +HCZ4DKqSQIgKnFMdLRQ37xLBVVXzD6Vh7RAScH2xKkT4iLnPOO63NFwLqkGL2DN
  IRENNm4L6nnOo+8zspzeloUtUIZV8LTypKCGFwZMspCYQi4l7dYfHzT7+qYqy1fh
  q3i7T4tHPkfUcCx9ZeJoG8Dk9+/JgIF5bGQw3wANx63LLBfp8swJ4oMcfq7SU3wK
  qRpZOl6ujd1TUJLNc/m9IpYq+dLhkaf5VHW+wYaztQ==
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDVzCCAj+gAwIBAgIQUC9RIP/uwR9rbyAFWGecljANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMwNTExMTkxMjQ1WhcNMjQw
  NTEwMTkxMjQ1WjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMMEnNv
  Y0B0ZXJyYWVhZ2xlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
  ANHNI1Nj57p2sudwFiJ5ip5cmMs3k9ibdzWYeEvCXrqUOT3BR7nJHRSrj81TG268
  2NRgNOUpLWPuMCMu9J1VKinu2MpsO6YiUGZJ//YuX6LsgUIDV5vQdB/IHcxwVCbo
  QTHo5/N+QkSlU0Ut69hDwMY0YMxXjM3P0m6xap7y6psM3Mh7c+XEB/LQRJEeL5KT
  8XjBnnOotyoXeSbTD3OB5GEfFblirptPuwfWQcrSreeon5p1uTn9IcGV5Rg5UL38
  ig/8wX4Ga3+xl/Wg4PXvMbBoHJetniCaCLZvgcQE5RTuAN6Nl9bMW2XANdJfNQdK
  oR4TVnMCkjADerEeD329lb8CAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
  JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
  MBaAFEqTzW38qoytOoVmT6dpFN44uQ5VMB0GA1UdEQQWMBSCEnNvY0B0ZXJyYWVh
  Z2xlLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAFUFE3Bu2aYK9lC3t2hXSHlnTgdAM
  0uLfJCS4PlIzYnjto1fmrS66rKS8HK6aAKZDAtvWyd9s3cNjxMu2f0qgOtVBB7fB
  jnlGtuOsYd9OUvJMlIuVHJHC01TRfGBbH0YSNR3e4+cKvWGLNQdfSDfCcpml9MZQ
  tPOCSR5kXNZ9+ciAgd4uYL0xIGcg4dc1WLBuxlU8FVkAYEJjVFchP+xBXAWhK2MZ
  ycsgGS/P93ukGIREuJSujLB8BMC3vFSnHC9N/Ct2DherdG5ZPCnKQIeu5OsSlafj
  4mEEHdfqf0/UNB2svZSKpoRUI3/iBfQIM5SUjoF2f4qbew/Jwh5v5Xt2hg==
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEogIBAAKCAQEA0c0jU2Pnunay53AWInmKnlyYyzeT2Jt3NZh4S8JeupQ5PcFH
  uckdFKuPzVMbbrzY1GA05SktY+4wIy70nVUqKe7Yymw7piJQZkn/9i5fouyBQgNX
  m9B0H8gdzHBUJuhBMejn835CRKVTRS3r2EPAxjRgzFeMzc/SbrFqnvLqmwzcyHtz
  5cQH8tBEkR4vkpPxeMGec6i3Khd5JtMPc4HkYR8VuWKum0+7B9ZBytKt56ifmnW5
  Of0hwZXlGDlQvfyKD/zBfgZrf7GX9aDg9e8xsGgcl62eIJoItm+BxATlFO4A3o2X
  1sxbZcA10l81B0qhHhNWcwKSMAN6sR4Pfb2VvwIDAQABAoIBAG+Kq9xbAkl9cBJh
  4jLEAbG+MzHfw4fm59Mj09kbZre1tFUj3FlnFkH2EIcuRyhx2KnY2GZ5pPs7GHas
  MTswmzEeHj5ImtHx7mLjtuUQtKHvMa2CD2L0ybhX8ZfOpL7mvjqlxCQNnXfXmdTu
  3DPnmacHE+uwJFkLw6o8Qx5ssdRqZLBwRDwbvbSbHep8iSqdof/pcteuCxmWOl5U
  J6HDpOW3T2YcPS+5HFpCeevzPIslg9X4cErDUSQHgLmZyhn3tWwRpY/aUPqM9BI0
  9IND311zErKzXrKd9+QZXxttymWhveiMhe9c9JO8KMkSVNEb4G7Y2jXvcOfnCptD
  D+NWUdkCgYEA4MdwU0XHRtG9l+Rc/6g7v2Pwm2T8R0lMYGHm0CCkMrC7SDu/JxGA
  a+VYxTwrhGIfkxRBWg2he1zlwhs/FvJj1bpPuffpZ9RSoZKpvFgkKEKtNkt5vffU
  oeCvER51qc4oWZEMdgjWyuONYTtG0uHlr0xUVBvcsDwnRHEXKO6+XuUCgYEA7vEh
  MZCf2ZIn2k+8NzPoFj0VWbeUh9y6WGoQH837UhdljO1uBG1SheI3vsR4alfx/V7j
  MK2uAYTEyqTo2+vd8wfD5Y+uKu8e0QKN/6pchbZVErTA36cDjj697P4wptoIKCRR
  6GL78x5DZuiru7Dn8SU5MYEB/hUohiRNB2ma89MCgYAJEmOJKNbLF+nz+GZ8dvi6
  V7k9PE0mP2ISvcDIA5k85n8YgjjLxdwN/rqfczc6Z49oqzeb/9LVnME1HU5libDX
  zmYrVkMYSqxvEvFAxbnn2hENkOw/64GsatoF8dnD2astOjprhR3OIHLzSqYoGq/f
  bFA2+MzmW/clvv61SzVptQKBgDS1eoYNikWbiTEOb82ZpLPrK5+L8Lb7yRuh4gay
  EKOuR5eL9L4DQ7YHDhcGDi4fUmF7IhDl70GkgSjWsgt5f4+SAfPM+zW7ZAflUV+5
  vAk/DItA1l8/33fsfUcfV6om5K++O1dRJpUd8u5rmx6fSrsWZAR4mfDrx/G3Zkqh
  UC5DAoGAKGNgukiFsx0wslaHlhsn76Br6m8xkDZZxX2VhWbV8NKDNaU7qtNXArvx
  uRiyLjSb1BKVdj5n3Rvk1kwRLIs6JNdmXhokgJ7gMK4MLUX8FiBEb1oBv0SMlbSq
  AvmjcYM7tq/pmyVc2qwuGujk029evLSr3NC5BF33RsujK7orPhQ=
  -----END RSA PRIVATE KEY-----
api_connection_string: 192.168.14.9:8001
name: soc@terraeagle.com